language: python
python:
  - '3.9'
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
script:
  - pytest --cov=./

after_success:
  - bash <(curl -s https://codecov.io/bash)